using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Generics.Sample.Api.Models
{
    public class SampleEvent2Model:IEventModel
    {
        public int Order { get; set; }
        public bool IsAutogenerated { get; set; }
        public String Info { get; set; }
    }
}
